# Generated by Django 4.1.3 on 2022-12-05 12:45

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import padaria.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=14)),
                ('dataNascimento', models.DateField()),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', padaria.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('valorPedido', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Total')),
                ('valorProduto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Produto')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('quantidadeProduto', models.IntegerField(verbose_name='Quantidade Produto')),
            ],
            options={
                'verbose_name': 'Items Pedido',
                'verbose_name_plural': 'Items Pedido',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sabor', models.CharField(blank=True, max_length=100, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=7, null=True)),
                ('descricao', models.TextField()),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=padaria.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao-credito', 'Crédito'), ('cartao-debito', 'Débito')], default='dinheiro', max_length=20, verbose_name='Pagamento')),
                ('statusPedido', models.CharField(choices=[('preparando', 'Preparando'), ('concluido', 'Concluído'), ('entrega', 'Em Trânsito')], default='preparando', max_length=20, verbose_name='Status')),
                ('valorPedido', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Total')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('produtos', models.ManyToManyField(through='padaria.ItensPedido', to='padaria.produto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padaria.pedido'),
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padaria.produto'),
        ),
    ]
